# "docker-compose -f <compose name>.yaml"
# "docker-compose up -d" to run in background
version: "3"
services:
    mymongo:
        image: "mongo"
        hostname: "mongo"
        ports:
            - '27017:27017'
        entrypoint: ['/usr/bin/mongod']
        restart: always


    web_app:
        image: "omribenhur/web_app"
        depends_on:
            - mymongo
        ports:
            - "80:80"
        volumes:
            - ./app/secret.py:/app/secret.py
        restart: always
